"""Creating ponto and users tables

Revision ID: db132fa69dc3
Revises: 
Create Date: 2019-04-20 18:59:47.658665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db132fa69dc3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('username')
    )
    op.create_table('ponto',
    sa.Column('ponto_id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hour1', sa.Time(), nullable=True),
    sa.Column('hour2', sa.Time(), nullable=True),
    sa.Column('hour3', sa.Time(), nullable=True),
    sa.Column('hour4', sa.Time(), nullable=True),
    sa.Column('picture', sa.Time(), nullable=False),
    sa.Column('absence_reason', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('ponto_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ponto')
    op.drop_table('users')
    # ### end Alembic commands ###
